mkcd() {
  # -- signifies end of command line options. So if I for some reason wanted to
  # pass an argument that starts with a dash it won't be read as a command
  # option, but an actual argument
  mkdir -p -- "$1" && cd -- "$1"
}

cdl() {
  args=
  directory=
  for arg in "$@"; do
    if [[ "$arg" = -* ]]; then
      if [ ! -z "$args" ]; then
        args+=" $arg"
      else
        args+="$arg"
      fi
    else
      directory=$arg
    fi
  done

  if [ -z "$args" ]; then
    cd "$directory" && ls
  else
    cd "$directory" && ls $args
  fi
}

alias fzfi='nvim $(fzf -m --preview="bat --color=always {}")'
